Fixing test in git-check-branch: replaced .. by ...
Otherwise the test fails if there are new commits in origin. However, it
should only fail if there are new local commits.

diff --git a/git-check-branch b/git-check-branch
--- a/git-check-branch
+++ b/git-check-branch
@@ -20,7 +20,9 @@ fi
 if [[ $(cat .git/HEAD | cut -c1-4) != "ref:" ]]; then
     ## detached head cannot be remote tracking branch...
     ## ...but: if there are no new commits, we can safely ignore this
-    if [[ $(git diff origin..  --quiet || echo "FAIL") == "FAIL" ]]; then
+    ## FIXME: this test only succeed if the new commit is actually
+    ##        checked out
+    if [[ $(git diff origin...  --quiet || echo "FAIL") == "FAIL" ]]; then
 	echo "Error in $PWD:"
 	echo " Detached head and new commits. Attach the HEAD by creating"
         echo " a new branch or risk losing the commits."
