Did a lot of work, added a README and most of the functionality work now.

diff --git a/git-attach-head b/git-attach-head
--- a/git-attach-head
+++ b/git-attach-head
@@ -1,5 +1,7 @@
 #!/bin/bash -e
 ## Attaches HEAD if commit and top of branch are identical anyway
+## Fast forwards local branch if HEAD matches top of remote branch.
+## If argument -w is given: warn if HEAD cannot be attached
 
 ## TODO: do some error checking?
 
@@ -8,12 +10,39 @@ if [[ $(cat .git/HEAD | cut -c1-4) == "ref:" ]]; then
     exit 0
 fi
 
+## get arguments
+while getopts ":w" opt; do
+    case $opt in
+	w)
+	    w=1
+	    #echo "-f was triggered!" >&2
+	    ;;
+	\?)
+	    # ignore this
+	    #echo "Invalid option: -$OPTARG" >&2
+	    ;;
+  esac
+done
+
 HEAD=`git rev-parse HEAD`
-branch=`git what-branch $HEAD 2> /dev/null || git what-branch --allbranches $HEAD`
+branch=`git what-branch --quiet $HEAD 2> /dev/null || git what-branch --quiet --allbranches $HEAD 2> /dev/null || echo ""`
+if [[ "$branch" == "" ]]; then
+    exit 0;
+fi
 HEADofbranch=`git rev-parse $branch`
 
 if [ "$HEAD" == "$HEADofbranch" ]; then
-    git checkout --quiet ${branch##remotes/*/} > /dev/null
+    lbranch=${branch##remotes/*/}
+    git checkout --quiet "$lbranch" > /dev/null
+    if [ "$branch" != "$lbranch" ]; then
+	echo "Fast forwarding local branch"
+	git merge --quiet --ff-only $HEAD
+    fi
+else
+    if [[ "$w" ]]; then
+	echo "Warning in $PWD:"
+	echo " Cannot attach HEAD. There are probably unmerged updates available. Go (\"cd\") there and use \"git brach -v\" list available branches. Switch branches with \"git checkout <branchname>\"."
+    fi
 fi
 
 ## else rewind local branch and do the checkout ??
diff --git a/git-ccommit b/git-ccommit
--- a/git-ccommit
+++ b/git-ccommit
@@ -5,13 +5,18 @@
 ## nor ignored.
 
 a=0
+q=0
 
 ## ToDo: what about --all???
-while getopts ":a" opt; do
+while getopts ":aq" opt; do
     case $opt in
 	a)
 	    a=1
 	    #echo "-a was triggered!" >&2
+	    ;;
+	q)
+	    q=1
+	    #echo "-q was triggered!" >&2
 	    ;;
 	\?)
 	    # ignore this
@@ -21,15 +26,36 @@ while getopts ":a" opt; do
 done
 
 if [ $a -ne 1 ] && ! git diff --no-ext-diff --quiet --exit-code; then
-    echo "Warning, there are unstaged changes to tracked files in this directory."
+    echo "Warning in $PWD:"
+    echo " Unstaged changes to files under version control."
+    echo " To add, use option -a to stage or add files manually with git add <file>."
 fi 
    
 ## check if -a or --all option is set
+# echo "Hello $PWD $a"
+
+# if ([ $a -eq 1 ] && ! git diff --no-ext-diff --quiet --exit-code); then
+#     echo "yes, do it!"
  
 ## commit if dirty
 if ([ $a -eq 1 ] && ! git diff --no-ext-diff --quiet --exit-code) || (git rev-parse --quiet --verify HEAD >/dev/null && ! git diff-index --cached --quiet HEAD --); 
 then
+    ## check for detached head
+    if [[ $(cat .git/HEAD | cut -c1-4) != "ref:" ]]; then
+	echo "Error in $PWD:"
+	echo " Refused to commit in detached head state. Use \"git rcheckout <branchname>\" to attach HEAD. List branches with \"git branch -v\"."
+	exit 1
+    fi
+
+    echo "Commiting in $PWD..."
     git commit "$@"
+    
+    if [ -f .gitmodules ]; then
+	## Syncronize submodules if necessary
+	git converge-submodules
+    fi
 else
-    echo "Directory clean, skipping"
+    if [ $q -ne 1 ]; then
+	echo "Directory clean, skipping"
+    fi
 fi
diff --git a/git-check-clean b/git-check-clean
--- a/git-check-clean
+++ b/git-check-clean
@@ -1,9 +1,39 @@
 #!/bin/bash -e
 ## check for modified content and uncommited changes
 
-if ! git diff --no-ext-diff --quiet --exit-code || (git rev-parse --quiet --verify HEAD >/dev/null && ! git diff-index --cached --quiet HEAD --); then
-    echo "Error in $PWD:"
-    echo " There are unstaged changes or untracked files not in .gitignore."
-    echo " Try to run \"make clean"\"
-    exit 1
+## Tests copied from bash completion support for core Git.
+## by Shawn O. Pearce <spearce@spearce.org>
+
+## Check unstaged changes
+if ! git diff --no-ext-diff --quiet --exit-code; then
+    ## not in submodules
+    if ! git diff --no-ext-diff --quiet --ignore-submodules --exit-code; then
+	output=" There are unstaged changes. Use \"git add <file>\" to add.
+"
+    fi
+    ## in submodules
+    ## get submodules
+    while read line; do
+	sub="$sub ${line#submodule.*.path }"
+    done < <(git config -f .gitmodules --get-regexp "submodule\..*\.path")
+    if ! git diff --no-ext-diff --quiet --exit-code $sub; then
+	output="$output There is modified content in submodules.
+"
+    fi
+fi
+
+if (git rev-parse --quiet --verify HEAD >/dev/null && ! git diff-index --cached --quiet HEAD --); then
+    output="$output There are uncommited files. Use \"git rcommit\" or \"git commit\" to commit.
+"
 fi 
+
+if [ -n "$(git ls-files --others --exclude-standard)" ]; then
+    output="$output There are untracked files not in .gitignore. Try \"make clean\" to remove temporary files.
+"
+fi
+
+if [[ "$output" ]]; then
+    echo "Error in $PWD:"
+    echo -n "$output"
+    exit 1
+fi
diff --git a/git-check-unpushed b/git-check-unpushed
--- a/git-check-unpushed
+++ b/git-check-unpushed
@@ -1,18 +1,40 @@
 #!/bin/bash -e
-## Check for unpushed commits in current branch
+## Check for unpushed commits in remote tracking branches
+## if argument -p is given: does not exit with a failure
 
-## Switch to directory
-if [[ "$1" ]]; then
-    cd "$1"
+while getopts ":p" opt; do
+    case $opt in
+	p)
+	    p=1
+	    #echo "-p was triggered!" >&2
+	    ;;
+	\?)
+	    # ignore this
+	    #echo "Invalid option: -$OPTARG" >&2
+	    ;;
+  esac
+done
+
+## cycle all branches
+while read line; do
+    ##echo "$line"
+    branch=`expr "$line" : '\** *\([^ ]*\)'`
+    ##echo "$branch"
+    remote=`expr "$line" : '.*\[\(.*\)\]'` || continue
+    ##echo "$remote"
+    ## if we're ahead: branch will show it after ":" 
+    status=`expr "$remote" : '.*: ahead \(.*\)'` || continue
+    ##echo "$status"
+    unpushed="$unpushed Branch \"$branch\" is ahead $status commit(s).
+"
+done < <(git branch --no-color -vv 2> /dev/null)
+
+if [ "$unpushed" ]; then
+    if [[ $p -ne 1 ]]; then
+	echo "Error in $PWD:"
+	echo -n "$unpushed"
+	exit 1
+    fi
+    echo "In $PWD:"
+    echo -n "$unpushed"
 fi
-
-## can only check, if we are on a remote tracking branch
-git check-branch
-
-activebranch=`git name-rev --name-only HEAD`
-
-if [[ $(git log origin/$activebranch..$activebranch --oneline) != "" ]] ; then
-    echo "Error: unpushed commits"
-    exit 1
-fi
-
diff --git a/git-rpull b/git-rpull
--- a/git-rpull
+++ b/git-rpull
@@ -6,24 +6,35 @@
 ## e.g., merge the where there are local and remote changes
 
 ## check for modified content and uncommited changes
-git is-clean
+git check-clean
 
-## check for unpushed changes in submodules
-git submodule --quiet foreach --recursive git check-unpushed
+## check for unpushed commits in submodules
+if [ -f .gitmodules ]; then
+    unpushed=`git submodule --quiet foreach --recursive git check-unpushed -p`
+    if [[ "$unpushed" != "" ]]; then
+	echo "Error: Unpushed commits in submodules."
+	echo "$unpushed"
+	exit 1
+    fi
+fi
 ## git check-unpushed # no need to check in master
 
 ## do the pull
 ## git pull --recurse-submodules (does not work)
 git pull
 
-## if the pull fails because of local non-pushed commits, 
-## what to do? 
-
-## initialize submodules: cannot combine --init with --merge!!
-git submodule --quiet update --init --recursive
-## remove old submodule directories: 
-## this is more or less safe, since only ignored files might be deleted
-git submodule --quiet foreach git rm-orphaned-submodule-dirs
-git rm-orphaned-submodule-dirs
-## attach heads
-git submodule --quiet foreach --recursive git attach-head
+if [ -f .gitmodules ]; then
+    ## initialize submodules: cannot combine --init with --merge!!
+    git submodule --quiet update --init --recursive
+    ## remove old submodule directories: 
+    ## this is more or less safe, since only ignored files might be deleted
+    git submodule --quiet foreach git rm-orphaned-submodule-dirs
+    git rm-orphaned-submodule-dirs
+    ## attach heads
+    git submodule --quiet foreach --recursive git attach-head
+    ## fetch changes in submodules 
+    ## this is necessary since if the submodule commit did not change
+    ## in the super rep., then the submodule is not updated.
+    ## check-for-updates does this when using the -f switch
+    git check-for-updates -f
+fi
