Scripts are partially Windows compatible. Had to remove process substitution. Also using ( ) in scripts and exit 1 within did not cause script to stop in git-bash on windows.

diff --git a/git-attach-head b/git-attach-head
--- a/git-attach-head
+++ b/git-attach-head
@@ -27,7 +27,8 @@ done
 HEAD=`git rev-parse HEAD`
 branch=`git what-branch --quiet $HEAD 2> /dev/null || git what-branch --quiet --allbranches $HEAD 2> /dev/null || echo ""`
 if [[ "$branch" == "" ]]; then
-    exit 0;
+    echo "Error: git-what-branch failed or is missing."
+    exit 1;
 fi
 HEADofbranch=`git rev-parse $branch`
 
diff --git a/git-check-branch b/git-check-branch
--- a/git-check-branch
+++ b/git-check-branch
@@ -1,23 +1,27 @@
 #!/bin/bash -e
 ## Check if we're on a remote tracking branch
 
+if [[ $(cat .git/HEAD | cut -c1-4) != "ref:" ]]; then
+    ## detached head cannot be remote tracking branch...
+    echo "Error in $PWD:"
+    echo " Detached head. Use git attach-head or git pull to update submodule."
+    exit 1
+fi
+
+tmp=`git branch --no-color -vv 2> /dev/null`
 while read line; do
     if [[ "${line:0:1}" != "*" ]]; then
 	continue
     fi
-    ##echo "$line"
+    #echo "$line"
     remote=`expr "$line" : '.*\[\(.*\)\]'` || nontracking=0
-done < <(git branch --no-color -vv 2> /dev/null)
+done <<< "$tmp"
 
 activebranch=`git name-rev --name-only HEAD`
 
 if [[ "$nontracking" ]]; then
     ## if we're here: fail
     echo "Error in $PWD:"
-    if [[ "$activebranch" =~ "~" ]]; then
-	echo " Detached head. Use git attach-head or git pull to update submodule."
-    else
-	echo " Branch \"$activebranch\" is not a remote tracking branch."
-    fi
+    echo " Branch \"$activebranch\" is not a remote tracking branch."
     exit 1
 fi
