Fixing scripts to work if called not from the toplevel directory.

diff --git a/git-converge-submodules b/git-converge-submodules
--- a/git-converge-submodules
+++ b/git-converge-submodules
@@ -50,6 +50,13 @@ while getopts ":fq" opt; do
   esac
 done 
 
+## ensure we are in the toplevel directory
+cdup=$(git rev-parse --show-toplevel) &&
+cd "$cdup" || {
+    echo >&2 "Cannot chdir to $cdup, the toplevel of the working tree"
+    exit 1
+}
+
 if [ -f .gitmodules ]; then
     ## Check if local and remote have diverged
     ## in the submodules and merge if necessary
diff --git a/git-fix-submodules b/git-fix-submodules
--- a/git-fix-submodules
+++ b/git-fix-submodules
@@ -19,6 +19,13 @@ EOF
     exit 0;
 fi
 
+## ensure we are in the toplevel directory
+cdup=$(git rev-parse --show-toplevel) &&
+cd "$cdup" || {
+    echo >&2 "Cannot chdir to $cdup, the toplevel of the working tree"
+    exit 1
+}
+
 ## continue only if there are submodules
 if [ -f .gitmodules ]; then 
     ## check for modified content and uncommitted changes
diff --git a/git-rdiff b/git-rdiff
--- a/git-rdiff
+++ b/git-rdiff
@@ -17,6 +17,13 @@ EOF
 fi
 
 
+## ensure we are in the toplevel directory
+cdup=$(git rev-parse --show-toplevel) &&
+cd "$cdup" || {
+    echo >&2 "Cannot chdir to $cdup, the toplevel of the working tree"
+    exit 1
+}
+
 ## continue silently, if there are unstaged changes
 ## we assume that such directories have already been merged.
 ## TODO: also show difference if fast forward is possible.
diff --git a/git-rfetch b/git-rfetch
--- a/git-rfetch
+++ b/git-rfetch
@@ -28,6 +28,13 @@ if [[ "$1" ]]; then
     fi
 fi
 
+## ensure we are in the toplevel directory
+cdup=$(git rev-parse --show-toplevel) &&
+cd "$cdup" || {
+    echo >&2 "Cannot chdir to $cdup, the toplevel of the working tree"
+    exit 1
+}
+
 ## check the super repository
 if [[ $(git fetch $dryrun 2>&1) != '' ]]; then
     output="There are updates available for the current repository.
diff --git a/git-rm-orphaned-submodule-dirs b/git-rm-orphaned-submodule-dirs
--- a/git-rm-orphaned-submodule-dirs
+++ b/git-rm-orphaned-submodule-dirs
@@ -18,6 +18,13 @@ EOF
     exit 0;
 fi
 
+## ensure we are in the toplevel directory
+cdup=$(git rev-parse --show-toplevel) &&
+cd "$cdup" || {
+    echo >&2 "Cannot chdir to $cdup, the toplevel of the working tree"
+    exit 1
+}
+
 ## find submodule urls not in .gitmodules:
 git config --get-regexp submodule.*url |
 while read key url; do
diff --git a/git-rm-submodule b/git-rm-submodule
--- a/git-rm-submodule
+++ b/git-rm-submodule
@@ -33,7 +33,15 @@ if [[ ! "$dir" || $(git ls-files --error-unmatch --stage -- "$dir" | grep -E '^1
     exit 1
 fi
 
-tdir=$PWD
+## get the full path of the submodule
+dir=$(git ls-files --full-name "$dir")
+## ensure that we are in the toplevel directory
+cdup=$(git rev-parse --show-toplevel) &&
+cd "$cdup" || {
+    echo >&2 "Cannot chdir to $cdup, the toplevel of the working tree"
+    exit 1
+}
+
 cd "$dir"
 ## check if submodule is clean
 git check-clean || exit 1
@@ -43,7 +51,7 @@ git check-unpushed || exit 1
 git check-non-tracking || exit 1
 ## find the real git-dir (might be git-file, for v.1.7.8 compatibility)
 gitdir=$(git rev-parse --git-dir)
-cd "$tdir"
+cd "$cdup"
 
 ## seems we're safe, so start removing
 ## get submodule url
diff --git a/git-rpull b/git-rpull
--- a/git-rpull
+++ b/git-rpull
@@ -36,6 +36,13 @@ EOF
     exit 1
 fi
 
+## ensure that we are in the toplevel directory
+cdup=$(git rev-parse --show-toplevel) &&
+cd "$cdup" || {
+    echo >&2 "Cannot chdir to $cdup, the toplevel of the working tree"
+    exit 1
+}
+
 ## check for unpushed commits in submodules
 if [ -f .gitmodules ]; then
     unpushed=`git submodule --quiet foreach --recursive git check-unpushed -p`
