Routing all errors and warnings to stderr instead of stdout.

diff --git a/git-check-clean b/git-check-clean
--- a/git-check-clean
+++ b/git-check-clean
@@ -129,11 +129,11 @@ fi
 
 if [[ "$output" ]]; then
     if [[ "$warn" ]]; then
-	echo -n "Warning in $PWD: 
+	echo >&2 -n "Warning in $PWD: 
 $output"
 	exit 0
     else
-	echo 2>&1 -n "Error in $PWD:
+	echo >&2 -n "Error in $PWD:
 $output"
 	exit 1
     fi
diff --git a/git-rfetch b/git-rfetch
--- a/git-rfetch
+++ b/git-rfetch
@@ -23,7 +23,8 @@ if [[ "$1" ]]; then
     if [[ "$1" == "--dry-run" ]]; then
 	dryrun="--dry-run"
     else 
-	echo >&2 "Error: rfetch does only accept the argument --dry-run, nothing else."
+	echo >&2 "Error: rfetch does only accept the argument --dry-run,
+    nothing else."
     fi
 fi
 
